#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 374209-web-01 100.26.228.118:80 check\n\tserver 374209-web-02 54.158.189.35:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
